### ISSUE TITLE
ios retrocompat

### ISSUE THREAD

**Issue by flutter-painter** [RafaelBarbosatec/qr_code_dart_scan#1]
ios black screen on preview :
Encountered error "The selected imageFormatGroup is not supported by iOS. Defaulting to brga8888"
linked with https://github.com/flutter/flutter/issues/86308
fixed by setting ResolutionPreset to medium l.87
controller = CameraController(camera, ResolutionPreset.medium);

Super repo 👍

**Comment by RafaelBarbosatec** [comment]
Thanks for this report!
I'll adds configuration of the resolution to turn more easy this kind of configuration.

**Comment by RafaelBarbosatec** [comment]
Now you can pass `resolutionPreset` in `QRCodeDartScanView`.
