### ISSUE TITLE
What an awesome Package!  Any chance you'll update the dependencies?

### ISSUE THREAD

**Issue by longtimedeveloper** [RafaelBarbosatec/qr_code_dart_scan#11]
Greetings, 

Thank you for an awesome QR Code Scanner!  So easy to use, thank you.

Any chance you'll update the package dependencies to the latest?

Thank you and have a great day,

Karl

**Comment by RafaelBarbosatec** [comment]
Hi @longtimedeveloper !
Thanks so much!
I'm on vacation at the moment. 
I will update this package when back to work.

**Comment by RafaelBarbosatec** [comment]
Updated! version `0.7.4` available
