### ISSUE TITLE
the class CameraImage does not have unnamed constructor

### ISSUE THREAD

**Issue by aimeykra** [RafaelBarbosatec/qr_code_dart_scan#17]
I am trying to use this package to simply scan a QR code and get the text content in Dart code. I do not want to display a view widget . I just need the text result and do something with it.

This line of code:
 Result? result = await decoder.decodeCameraImage(CameraImage());

Is throwing Dart parse error : class CamareImage does not have unnamed constructor.  I checked the camera.dart package and indeed  the constructor to use is CameraImage.fromPlatformInterface(). But do i get the  CameraImageData parameter that i need to pass to this named constructor?

Thanks for feedback.
Kay

**Comment by RafaelBarbosatec** [comment]
Hi @aimeykra !
Thanks for contacting!
So, if you want just decode a image file to get the qrcode information, you can use `decoder.decodeFile(XFile())`
