### ISSUE TITLE
How can I change TypeCamera programmatically?

### ISSUE THREAD

**Issue by scognito** [RafaelBarbosatec/qr_code_dart_scan#20]
I see that I can change the Scan Type (live / take picture), but not the camera type (front / back) programmatically. Is it inteded?

Cool package btw, thanks!

**Comment by RafaelBarbosatec** [comment]
Hi @scognito !
Thanks for bring this case. At the moment it is not possible, but I will take a look a way to implements this feature.

**Comment by RafaelBarbosatec** [comment]
Available in latest release.
Just pass the controller and call changeCamera method

**Comment by scognito** [comment]
Cool works!

I just get this error while changing camera, but it works!

The following CameraException was thrown building ValueListenableBuilder<CameraValue>(state: _ValueListenableBuilderState<CameraValue>#d4bda):
CameraException(Disposed CameraController, buildPreview() was called on a disposed CameraController.)

**Comment by yfming93** [comment]
> Cool works!
> 
> I just get this error while changing camera, but it works!
> 
> The following CameraException was thrown building ValueListenableBuilder(state: _ValueListenableBuilderState#d4bda): CameraException(Disposed CameraController, buildPreview() was called on a disposed CameraController.)

had The same issue.

**Comment by rafaelalmeidacloudwalk** [comment]
hi @yfming93 !
Which version do you use? IT was fixed in latest version.
