### ISSUE TITLE
Rescan an already scanned QR code

### ISSUE THREAD

**Issue by scognito** [RafaelBarbosatec/qr_code_dart_scan#21]
I'm using the live mode.
When I scan a QR code and then a different one, everything works fine.
When I scan a QR code, then move the camera around, and try to scan the same again, it is not scanned: I have to scan another one and then the old one can be scanned again.
Is it intended maybe to avoid multiple scan almost simultaneously? If it is, can at least an option be set? Or maybe I'm doing something wrong?
This is my code, very simple:
```
QRCodeDartScanView(
                typeCamera: typeCamera,
                scanInvertedQRCode: true,
                typeScan: TypeScan.live,
                heightPreview: heightPreview,
                widthPreview: widthPreview,
                onCapture: (Result result) {
                  print(result.text);
                },
              ),
```

In my app I want to scan the same QR code more than one time, I'm using a debouncing function to avoid to scan after 1-2 seconds.

Thanks for this awesome library.

**Comment by RafaelBarbosatec** [comment]
Hi @scognito !
Thanks for contacting!
Great, it's a good idea, I'll implements that to the next release.

**Comment by RafaelBarbosatec** [comment]
Fixed in latest release

**Comment by scognito** [comment]
How can I use this feature? Thanks

**Comment by scognito** [comment]
Any update on this?

**Comment by miitiicoo** [comment]
> Fixed in latest release

Hey Rafael i need this fix too! How can i use it?

**Comment by RafaelBarbosatec** [comment]
Hi @scognito and @miitiicoo !
Just use. Now we have a param `intervalScan`. The default value is `1 second`. And was removed the validation to not scan the same barCode twice or more consecutive.

**Comment by scognito** [comment]
you can close this :)
