### ISSUE TITLE
preview looks stretched

### ISSUE THREAD

**Issue by mirkancal** [RafaelBarbosatec/qr_code_dart_scan#22]
I just passed QRCodeDartScanView to Scaffold's body and image seems stretched. Is there any easy fix for that?

I see that it is possible to set height and width of preview but camera height and width is not same with device's. Something handler to get image resolutions when camera is on would fix that i guess.

**Comment by RafaelBarbosatec** [comment]
Hi @mirkancal !
Could you share the printscreen?
What version do you using?

**Comment by mirkancal** [comment]
Hi, updated from 0.7.3 to 0.7.7 and changed the quality to ultrahigh, now it seems a lot better
