### ISSUE TITLE
update depends on camera ^0.11.0+1

### ISSUE THREAD

**Issue by yfming93** [RafaelBarbosatec/qr_code_dart_scan#25]
Because qr_code_dart_scan >=0.7.4 depends on camera ^0.10.5+9 and app depends on camera ^0.11.0+1, qr_code_dart_scan >=0.7.4 is forbidden.
So, because app depends on qr_code_dart_scan ^0.8.0, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on camera: flutter pub add camera:^0.10.6

**Comment by RafaelBarbosatec** [comment]
The camera was updated in the last version.
