### ISSUE TITLE
Take a time to scan QRCode in Android

### ISSUE THREAD

**Issue by ChiragLiveu** [RafaelBarbosatec/qr_code_dart_scan#34]
We are using this package in our project and are encountering an issue with scanning QR codes on Android. The scanning process takes significantly longer to return results compared to iOS. Additionally, it would be helpful to include a feature for toggling the flashlight on and off during the scan. Could this functionality be added?

**Comment by RafaelBarbosatec** [comment]
Hi @ChiragLiveu !
Thanks for this reporting. I will analyze this point. There's no difference abou android and IOS implementation.
About flashlight, it's is possible. Just pass a controller to the widget and there you can access to Camera controller that you able turn on or turn off the flashlight.
