### ISSUE TITLE
How to on flash during scanning is it available ??

### ISSUE THREAD

**Issue by pankaj1101** [RafaelBarbosatec/qr_code_dart_scan#38]

**Comment by RafaelBarbosatec** [comment]
Hi @pankaj1101 !
Yes it is possible.
Do you can pass a controller(QRCodeDartScanController) to the widget. And then you have access to CameraController. With this controller you can control the flash.

**Comment by RafaelBarbosatec** [comment]
I will improve this part adding options about flash in our controller.

**Comment by pankaj1101** [comment]
I Modified your package code and added toggleFlash function now it is working great

**Comment by pankaj1101** [comment]
// Method to toggle flash
  Future<void> toggleFlash() async {
    if (cameraController == null || !cameraController!.value.isInitialized) {
      return; // Ensure the camera is initialized
    }

    final currentFlashMode = cameraController!.value.flashMode;

    // Determine the next flash mode
    FlashMode nextFlashMode;
    switch (currentFlashMode) {
      case FlashMode.off:
        nextFlashMode = FlashMode.torch;
        break;
      case FlashMode.torch:
        nextFlashMode = FlashMode.off;
        break;
      default:
        nextFlashMode = FlashMode.off;
        break;
    }

    try {
      await cameraController
          ?.setFlashMode(nextFlashMode); // Set the new flash mode
      state.value =
          state.value.copyWith(flashMode: nextFlashMode); // Update state
    } catch (e) {
      debugPrint('Error toggling flash: $e');
    }
  }
  
  Using this i got what i want.

**Comment by RafaelBarbosatec** [comment]
Thanks! It is Available in version Version 0.9.4
